### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by conorsheehan** [conorsheehan/wedding-save-the-date#5]

**Comment by richardbmx** [comment]
@conorsheehan Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new Favicon for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by conorsheehan** [comment]
Hey @richardbmx - Sorry, this is a personal project that I'm probably going to take on as a solo contributor. Thank you anyway!
